### ISSUE TITLE
how to load images from scss file

### ISSUE THREAD

**Issue by sylwesterdigital** [taniarascia/webpack-boilerplate#54]
Thanks for your boiler plate. It would be nice to have also a loader for images from _.scss files

this simply does not work.
```
 background-image: url('./images/copy3.png');
```

**Comment by taniarascia** [comment]
Sorry for the delay, I ensured this works in dev and prod.

```js
// Test a background image url in CSS
const imageBackground = document.createElement('div')
imageBackground.classList.add('image')
```

```css
.image {
  display: inline-block;
  height: 100px;
  width: 100px;
  background-image: url('~assets/example.png');
  background-size: cover;
}
```
